server:
  servlet:
    context-path: "/demo-ai/v1"

spring:
    application:
        name: demo
    datasource:
        url: jdbc:mysql://${DbUrl}/SpringIa?createDatabaseIfNotExist=true
        username: ${UserDb}
        password: ${password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
    ai:
        mcp:
            server:
                base-url: ${server.servlet.context-path}
                sse-endpoint: /sse
                sse-message-endpoint: /mcp/message
    